name: 'GDS 2D and 3D'

on:
  push:
    branches:
      - main

jobs:
  GDS2Graphics:
    runs-on: ubuntu-20.04  # Configuración para Ubuntu 20.04

    steps:

    - name: Check out repository
      uses: actions/checkout@v4

    # Install packages for 'Render PNG from GDS' step:
    - name: Install prerequisites
      uses: awalsh128/cache-apt-pkgs-action@latest
      with:
        packages: librsvg2-bin pngquant cairosvg
        version: test

    - name: Install Python dependencies
      run: |
        python3 -m pip install --upgrade pip
        python3 -m pip install gdstk

    - name: Use gds2png script
      run: |
        python3 gds2png.py

    - name: Upload gds_render (png) artifact
      uses: actions/upload-artifact@v4
      with:
        name: gds_render_png
        path: 'gds_render.png'

#GDS to GTLF Process

    - name: GDS3D
      uses: actions/checkout@v4
      with:
        repository: mbalestrini/GDS2glTF
    
    - name: Python version
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        cache: 'pip' # caching pip dependencies

    - name: Install Python dependencies
      run: |
        python -m pip install numpy gdspy triangle pygltflib

    - name: Create gh-pages directory
      run: mkdir -p gh-pages

    - name: Rename GDS file
      run: |
        GDS_FILE=$(ls ./gds/*.gds | head -n 1) # Encuentra el primer archivo .gds
        if [ -z "$GDS_FILE" ]; then
          echo "Error: No GDS file found in the gds/ directory."
          exit 1
        fi
        cp "$GDS_FILE" gds/render.gds

    - name: Convert GDS to GLTF
      run: |
        python3 gds2gltf.py gds/render.gds

    - name: Move GLTF output
      run: cp render.gds.gltf gh-pages/render.gds.gltf

    - name: Upload gds_render (gtlf) artifact
      uses: actions/upload-artifact@v4
      with:
        name: gds_render_gtlf
        path: 'render.gds.gltf'


      