name: 'GDS 2D and 3D'

on:
  push:
    branches:
      - main

jobs:
  GDS2PNG:
    runs-on: ubuntu-20.04  # Configuración para Ubuntu 20.04

    steps:

    - name: Check out repository
      uses: actions/checkout@v4

    # Install packages for 'Render PNG from GDS' step:
    - name: Install prerequisites
      uses: awalsh128/cache-apt-pkgs-action@latest
      with:
        packages: librsvg2-bin pngquant cairosvg
        version: test

    - name: Install Python dependencies
      run: |
        python3 -m pip install --upgrade pip
        python3 -m pip install gdstk

    - name: Use gds2png script
      run: |
        python3 gds2png.py

    - name: Upload gds_render (png) artifact
      uses: actions/upload-artifact@v4
      with:
        name: gds_render_png
        path: 'gds_render.png'

  GDS2gTLF:
    runs-on: ubuntu-20.04  # Configuración para Ubuntu 20.04
    needs: GDS2PNG

    steps:

    - name: GDS3D
      uses: actions/checkout@v4
      with:
        repository: mbalestrini/GDS2glTF
    
    - name: Python version
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        cache: 'pip'

    - name: Install Python dependencies
      run: |
        python -m pip install numpy gdspy triangle pygltflib

    - name: List repository structure
      run: |
        echo "Current directory: $(pwd)"
        ls -R ${{ github.workspace }}
        ls ${{ github.workspace }}/gds

    - name: Rename GDS file
      run: |
        GDS_FILE=$(ls ${{ github.workspace }}/gds/*.gds | head -n 1) 
        if [ -z "$GDS_FILE" ]; then
          echo "Error: No GDS file found in the gds/ directory."
          exit 1
        fi
        cp "$GDS_FILE" gds/render.gds

    - name: Convert GDS to GLTF
      run: |
        python3 gds2gltf.py gds/render.gds

    - name: Upload gds_render (gtlf) artifact
      uses: actions/upload-artifact@v4
      with:
        name: gds_render_gtlf
        path: 'render.gds.gltf'

  GithubSite:
    runs-on: ubuntu-20.04  # Configuración para Ubuntu 20.04
    needs: GDS2gTLF

    steps: 

    - name: Create gh-pages directory
      run: mkdir -p gh-pages

    - name: Upload gds_render (png) artifact
      uses: actions/upload-artifact@v3
      with:
        name: gds_render_png
        path: './gh-pages/gds_render.png'

    - name: Upload gds_render (png) artifact
      uses: actions/upload-artifact@v3
      with:
        name: gds_render_gtlf
        path: './gh-pages/gds_render.png'