name: 'GDS 2D and 3D'

on:
  push:
    branches:
      - main

jobs:
  GDS2PNG:
    runs-on: ubuntu-20.04  # Configuración para Ubuntu 20.04

    steps:
    - name: Check out repository
      uses: actions/checkout@v4

    # Install packages for 'Render PNG from GDS' step:
    - name: Install prerequisites
      uses: awalsh128/cache-apt-pkgs-action@latest
      with:
        packages: librsvg2-bin pngquant cairosvg
        version: test # I think naming a version builds a reusable packages cache for that name.

    - name: Install Python dependencies
      run: |
        python3 -m pip install --upgrade pip
        python3 -m pip install gdstk

    - name: Use gds2png script
      run: |
        python3 gds2png.py

    - name: Upload gds_render (png) artifact
      uses: actions/upload-artifact@v4
      with:
        name: gds_render
        path: 'gds_render.png'
  
  GDS2gTLF:
    runs-on: ubuntu-20.04  # Configuración para Ubuntu 20.04

    steps:

    - name: GDS3D
        uses: actions/checkout@v4
        with:
          repository: mbalestrini/GDS2glTF
    
    - name: Python version
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip' # caching pip dependencies

    - name: Install Python dependencies
      run: |
        python -m pip install numpy gdspy triangle pygltflib

    - name: Create gh-pages directory
      run: mkdir -p gh-pages

    - name: Download gds_render artifact
        uses: actions/download-artifact@v4
        with:
          name: gds_render
          path: 'gh-pages/gds_render.png'

    - name: Rename GDS file
      run: |
        echo 'Revisar si se copió'
        ls gh-pages/
        mv gds/*.gds render.gds

    - name: Convert GDS to GLTF
      run: |
        python3 gds2gltf.py gds/render.gds

    - name: Move GLTF output
      run: cp render.gds.gltf gh-pages/render.gds.gltf


      